version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: batchforge
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: batchforge_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
