services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: batchforge
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: batchforge_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://batchforge:password123@db:5432/batchforge_db
    volumes:
      - .:/app

volumes:
  pg_data:
